// vue-client/src/components/navigation/Sidebar/SidebarFooter.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, toRefs } from 'vue';
import { client } from '../../../http/client';
import { SystemStatus, statusService } from '../../../services/statusService';
import LeftArrowIcon from '../../icons/LeftArrowIcon.vue';
import QuestionMarkIcon from '../../icons/QuestionMarkIcon.vue';
import RightArrowIcon from '../../icons/RightArrowIcon.vue';

const props = defineProps<{
  isCollapsed: boolean;
}>();

defineEmits<{
  (e: 'update:isCollapsed'): void;
}>();

const { isCollapsed } = toRefs(props);
const status = ref(SystemStatus.None);
const footerClass = computed(() => {
  return isCollapsed.value ? 'container-collapsed' : 'container';
});
const statusStyle = computed(() => {
  let color = '#2fcc66';

  switch (status.value) {
    case SystemStatus.Critical:
      color = 'red';
      break;
    case SystemStatus.Major:
      color = 'orange';
      break;
    case SystemStatus.Minor:
      color = 'yellow';
      break;
    case SystemStatus.Maintenance:
      color = 'blue';
      break;
    case SystemStatus.None:
    default:
      break;
  }

  return {
    backgroundColor: color,
  };
});
const { getStatus } = statusService(client({ includeCredentials: false }));

const interval = ref(0);

onMounted(() => {
  interval.value = setInterval(async () => {
    const statusResult = await getStatus();
    if (statusResult.isSuccess) {
      status.value = statusResult.value.status;
    }
  }, 15000);

  getStatus().then(statusResult => {
    if (statusResult.isSuccess) {
      status.value = statusResult.value.status;
    }
  });
});

onUnmounted(() => {
  clearInterval(interval.value);
});
</script>

<template>
  <footer :class="footerClass">
    <div title="Collapse" class="footer-item">
      <button
        type="button"
        class="footer-icon-container"
        @click="$emit('update:isCollapsed')"
      >
        <RightArrowIcon v-if="isCollapsed" class="footer-icon" />
        <LeftArrowIcon v-else class="footer-icon" />
      </button>
    </div>
    <div title="Help" class="footer-item">
      <a href="/Help/OnspringDocumentation.htm" class="footer-icon-container">
        <QuestionMarkIcon class="footer-icon" />
      </a>
    </div>
    <div title="All Systems Operational" class="footer-item">
      <div class="footer-icon-container">
        <div class="status-icon" :style="statusStyle"></div>
      </div>
    </div>
  </footer>
</template>

<style scoped>
.container,
.container-collapsed {
  display: flex;
}

.container-collapsed {
  flex-direction: column-reverse;
}

.footer-item {
  display: flex;
  flex: 1 0 auto;
  border: 1px solid #536a9b;
  border-bottom: 0;
  justify-content: center;
  height: 60px;
  flex-shrink: 0;
}

.footer-item:hover {
  background-color: #5b627e;
}

.footer-icon-container {
  display: flex;
  align-items: center;
  justify-content: center;
  background: transparent;
  border: none;
  cursor: pointer;
}

.footer-icon {
  width: 30px;
  fill: #ffffff;
}

.status-icon {
  top: 4px;
  width: 24px;
  height: 24px;
  border: 2px solid #fff;
  background-color: #2fcc66;
  border-radius: 50%;
}
</style>

// react-client/src/components/navigation/Sidebar/SidebarFooter.tsx
import { useEffect, useState } from 'react';
import { client } from '../../../http/client';
import { SystemStatus, statusService } from '../../../services/statusService';
import styles from './SidebarFooter.module.css';

export default function SidebarFooter({
  isCollapsed,
  arrowButtonClickHandler,
}: {
  isCollapsed: boolean;
  arrowButtonClickHandler: () => void;
}) {
  const [status, setStatus] = useState(SystemStatus.None);
  const { getStatus } = statusService(client({ includeCredentials: false }));

  useEffect(() => {
    const interval = setInterval(async () => {
      const statusResult = await getStatus();
      if (statusResult.isSuccess) {
        setStatus(statusResult.value.status);
      }
    }, 15000);

    getStatus().then(statusResult => {
      if (statusResult.isSuccess) {
        setStatus(statusResult.value.status);
      }
    });

    return () => clearInterval(interval);
  }, []);

  function getStatusColor() {
    switch (status) {
      case SystemStatus.Critical:
        return 'red';
      case SystemStatus.Major:
        return 'orange';
      case SystemStatus.Minor:
        return 'yellow';
      case SystemStatus.Maintenance:
        return 'blue';
      case SystemStatus.None:
      default:
        return '#2fcc66';
    }
  }

  return (
    <footer
      className={isCollapsed ? styles.containerCollapsed : styles.container}
    >
      <div
        onClick={arrowButtonClickHandler}
        title="Collapse"
        className={styles.footerItem}
      >
        <button type="button" className={styles.footerIconContainer}>
          {isCollapsed ? (
            <svg
              className={styles.footerIcon}
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
            >
              <path d="M4,15V9H12V4.16L19.84,12L12,19.84V15H4Z" />
            </svg>
          ) : (
            <svg
              className={styles.footerIcon}
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
            >
              <path d="M20,9V15H12V19.84L4.16,12L12,4.16V9H20Z" />
            </svg>
          )}
        </button>
      </div>
      <div title="Help" className={styles.footerItem}>
        <a
          href="/Help/OnspringDocumentation.htm"
          className={styles.footerIconContainer}
        >
          <svg
            className={styles.footerIcon}
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
          >
            <path d="M11,18H13V16H11V18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,6A4,4 0 0,0 8,10H10A2,2 0 0,1 12,8A2,2 0 0,1 14,10C14,12 11,11.75 11,15H13C13,12.75 16,12.5 16,10A4,4 0 0,0 12,6Z" />
          </svg>
        </a>
      </div>
      <div title="All Systems Operational" className={styles.footerItem}>
        <div className={styles.footerIconContainer}>
          <div
            className={styles.statusIcon}
            style={{
              backgroundColor: getStatusColor(),
            }}
          ></div>
        </div>
      </div>
    </footer>
  );
}
