// vue-client/src/components/authentication/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { client } from '../../http/client';
import { authService } from '../../services/authService';
import { useUserStore } from '../../stores/userStore';
import LockIcon from '../icons/LockIcon.vue';
import ProfileIcon from '../icons/ProfileIcon.vue';
import AuthFormErrorContainer from './AuthFormErrorContainer.vue';
import AuthInput from './AuthInput.vue';

const { logUserIn } = useUserStore();
const { login } = authService(client());

type FormState = {
  username: string;
  password: string;
  errors: string[];
};

const formState = ref<FormState>({
  username: '',
  password: '',
  errors: [],
});

async function handleFormSubmit() {
  formState.value.errors = [];

  if (!formState.value.username) {
    formState.value.errors.push('Username is required');
  }

  if (!formState.value.password) {
    formState.value.errors.push('Password is required');
  }

  if (formState.value.errors.length) {
    return;
  }

  const loginResult = await login(
    formState.value.username,
    formState.value.password
  );

  if (loginResult.isFailed) {
    formState.value.errors.push(loginResult.error.message);
    return;
  }

  logUserIn(loginResult.value.token);
}
</script>

<template>
  <form @submit.prevent="handleFormSubmit">
    <AuthInput v-model="formState.username" type="text" placeholder="Username">
      <template #icon>
        <ProfileIcon />
      </template>
    </AuthInput>

    <AuthInput
      v-model="formState.password"
      type="password"
      placeholder="Password"
    >
      <template #icon>
        <LockIcon />
      </template>
    </AuthInput>

    <div class="action-container">
      <RouterLink class="forgot-password-link" to="/Public/ForgotPassword">
        Forgot Password
      </RouterLink>
      <button class="login-button" type="submit">Login</button>
    </div>

    <AuthFormErrorContainer :errors="formState.errors" />
  </form>
</template>

<style scoped>
.action-container {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.forgot-password-link {
  color: #fff;
  text-decoration: none;
  font-size: 11px;
}

.forgot-password-link:hover {
  text-decoration: underline;
}

.login-button {
  border: 0;
  background: #f7941d;
  color: #fff;
  padding: 7.5px 15px;
  border-radius: 3px;
  cursor: pointer;
}

.login-button:hover {
  background-color: #df8419;
}
</style>

// react-client/src/components/authentication/LoginForm.tsx
import { ChangeEvent, FormEvent, useReducer } from 'react';
import { BiSolidLock } from 'react-icons/bi';
import { ImUser } from 'react-icons/im';
import { Link } from 'react-router-dom';
import { useUserContext } from '../../hooks/useUserContext';
import { client } from '../../http/client';
import { authService } from '../../services/authService';
import AuthFormErrorsContainer from './AuthFormErrorsContainer';
import { AuthInput } from './AuthInput';
import styles from './LoginForm.module.css';

export default function LoginForm() {
  const { logUserIn } = useUserContext();
  const { login } = authService(client());

  type FormState = {
    username: string;
    password: string;
    errors: string[];
  };

  const initialFormState: FormState = {
    username: '',
    password: '',
    errors: [],
  };

  type FormActions =
    | { type: 'SET_USERNAME'; payload: { username: string } }
    | { type: 'SET_PASSWORD'; payload: { password: string } }
    | { type: 'SET_ERROR'; payload: { error: string } }
    | { type: 'CLEAR_ERRORS' };

  const reducer = (state: FormState, action: FormActions) => {
    switch (action.type) {
      case 'SET_USERNAME':
        return {
          ...state,
          username: action.payload.username,
        };
      case 'SET_PASSWORD':
        return {
          ...state,
          password: action.payload.password,
        };
      case 'SET_ERROR':
        return {
          ...state,
          errors: [...state.errors, action.payload.error],
        };
      case 'CLEAR_ERRORS':
        return {
          ...state,
          errors: [],
        };
      default:
        return state;
    }
  };

  const [formState, dispatch] = useReducer(reducer, initialFormState);

  async function handleFormSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    dispatch({
      type: 'CLEAR_ERRORS',
    });

    const errors: string[] = [];

    if (!formState.username) {
      errors.push('Username is required');
    }

    if (!formState.password) {
      errors.push('Password is required');
    }

    if (errors.length > 0) {
      errors.forEach(error => {
        dispatch({
          type: 'SET_ERROR',
          payload: { error },
        });
      });

      return;
    }

    const loginResult = await login(formState.username, formState.password);

    if (loginResult.isFailed) {
      dispatch({
        type: 'SET_ERROR',
        payload: { error: loginResult.error.message },
      });
      return;
    }

    logUserIn(loginResult.value.token);
  }

  function handleUsernameChange(event: ChangeEvent<HTMLInputElement>) {
    dispatch({
      type: 'SET_USERNAME',
      payload: { username: event.target.value },
    });
  }

  function handlePasswordChange(event: ChangeEvent<HTMLInputElement>) {
    dispatch({
      type: 'SET_PASSWORD',
      payload: { password: event.target.value },
    });
  }

  return (
    <form onSubmit={handleFormSubmit}>
      <AuthInput
        Icon={ImUser}
        type="text"
        placeholder="Username"
        value={formState.username}
        changeHandler={handleUsernameChange}
      />
      <AuthInput
        Icon={BiSolidLock}
        type="password"
        placeholder="Password"
        value={formState.password}
        changeHandler={handlePasswordChange}
      />
      <div className={styles.actionsContainer}>
        <Link className={styles.forgotPasswordLink} to="/Public/ForgotPassword">
          Forgot Password?
        </Link>
        <button className={styles.loginButton} type="submit">
          Login
        </button>
      </div>
      <AuthFormErrorsContainer errors={formState.errors} />
    </form>
  );
}
