// react-client/src/components/layouts/PublicLayout.tsx
import { CSSProperties, ReactNode } from 'react';
import dew from '../../assets/images/backgrounds/dew.jpg';
import kromlau from '../../assets/images/backgrounds/kromlau.jpg';
import marsh from '../../assets/images/backgrounds/marsh.jpg';

export function PublicLayout({ children }: { children: ReactNode }) {
  const backgroundImages = [dew, kromlau, marsh];
  const backgroundImage =
    backgroundImages[Math.floor(Math.random() * backgroundImages.length)];

  const styles: CSSProperties = {
    background: `url(${backgroundImage})`,
    height: '100vh',
    backgroundPosition: 'center center',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'cover',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  };

  return <main style={styles}>{children}</main>;
}

// vue-client/src/components/layouts/PublicLayout.vue
<script setup lang="ts">
import dew from '../../assets/images/backgrounds/dew.jpg';
import kromlau from '../../assets/images/backgrounds/kromlau.jpg';
import marsh from '../../assets/images/backgrounds/marsh.jpg';

const images = [dew, kromlau, marsh];
const randomImage = images[Math.floor(Math.random() * images.length)];
</script>

<template>
  <main class="container" :style="{ backgroundImage: `url(${randomImage})` }">
    <router-view></router-view>
  </main>
</template>

<style scoped>
.container {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100vh;
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}
</style>
